module(
    name = "rules_tf",
    version = "0.1.0",
)

bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "aspect_bazel_lib", version = "2.9.4")
bazel_dep(name = "platforms", version = "0.0.10")
bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.2")

tf = use_extension("//tf:extensions.bzl", "tf")
tf.toolchain(version = "1.14.4")
use_repo(
    tf,
    "tf_executable",
)

register_toolchains(
    "@tf_executable//:all",
)
