load(
    "@rules_tf//tf:defs.bzl",
    "tf_binary",
    "tf_init",
)

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "*.tf",
        ],
    ) + [
        #You have to create this
        #file if it doesnt exist
        "this.tfstate",
    ],
    visibility = ["//visibility:public"],
)

tf_init(
    name = "init",
    srcs = [
        "main.tf",
    ],
)

tf_binary(
    name = "tf",
    srcs = [":srcs"],
    init = ":init",
)
