module(
    name = "rules_tf_examples",
)

bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.2", dev_dependency = True)
bazel_dep(name = "rules_shell", version = "0.5.0")
bazel_dep(name = "aspect_bazel_lib", version = "2.9.4")

bazel_dep(name = "rules_tf")
local_path_override(
    module_name = "rules_tf",
    path = "../",
)

tf = use_extension("//tf:extensions.bzl", "tf")
tf.toolchain(version = "1.14.4")
use_repo(
    tf,
    "tf_executable",
)
