load(
    "@rules_tf//tf:defs.bzl",
    "tf_apply",
    "tf_init",
    "tf_plan",
)

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "*.tf",
            #You have to create this 
            #file if it doesnt exist
            "this.tfstate"
        ],
        allow_empty = True
    ) ,
    visibility = ["//visibility:__pkg__"]
)

tf_init(
    name = "init",
    srcs = [
        "main.tf",
    ],
)

tf_plan(
    name = "plan",
    srcs = [
      ":srcs",
    ],
    init = ":init",
    parallelism = "100",
    lock = False,
)

tf_apply(
    name = "apply",
    srcs = [
      ":srcs",
    ],
    init = ":init",
    plan = ":plan",
)
