load(
    "@rules_tf//tf:defs.bzl",
    "tf_apply",
    "tf_fmt_test",
    "tf_init",
    "tf_plan",
    "tf_validate_test",
)

filegroup(
    name = "srcs",
    srcs = glob(
        [
            "*.tf",
        ],
    ) + [
        "//modules",
        #You have to create this
        #file if it doesnt exist
        "this.tfstate",
    ],
    visibility = ["//visibility:public"],
)

tf_validate_test(
    name = "validate",
    srcs = [":srcs"],
    init = ":init",
)

tf_fmt_test(
    name = "fmt",
    srcs = [":srcs"],
)

tf_init(
    name = "init",
    srcs = [
        "main.tf",
        "//modules",
    ],
)

tf_plan(
    name = "plan",
    srcs = [
        ":srcs",
    ],
    init = ":init",
    #We do not lock here
    #because build rules run
    #in sandbox environments
    #in which files are immutable
    lock = False,
    parallelism = "100",
)

tf_apply(
    name = "apply",
    srcs = [
        ":srcs",
    ],
    init = ":init",
    plan = ":plan",
    visibility = ["//visibility:public"],
)
